---

env:
  es6: true
  node: true

overrides:
  -
    files:
      - '*.js'
    extends:
      - '@matthiaskunnen/eslint-config-base'

  -
    files:
      - 'src/**/*.ts'
    extends:
      - '@matthiaskunnen/eslint-config-typescript-node'

    parser: '@typescript-eslint/parser'

    parserOptions:
      project:
        - tsconfig.json
      sourceType: module
