---

env:
  es6: true
  node: true

overrides:
  -
    files:
      - '*.js'
    extends:
      - '@matthiaskunnen/eslint-config-base'

  -
    files:
      - 'src/**/*.ts'
    extends:
      - '@matthiaskunnen/eslint-config-typescript-node'

    parser: '@typescript-eslint/parser'

    parserOptions:
      project:
        - tsconfig.json
      sourceType: module

    rules:
      '@typescript-eslint/member-ordering':
        - error
        -
          default:
            memberTypes:
              -  public-static-field
              -  protected-static-field
              -  private-static-field
              -  public-instance-field
              -  protected-instance-field
              -  private-instance-field
              -  public-constructor
              -  protected-constructor
              -  private-constructor
              -  public-static-method
              -  protected-static-method
              -  private-static-method
              -  public-instance-method
              -  protected-instance-method
              -  private-instance-method
              -  signature
            order: alphabetically

